import { EntityPageConfig } from '../../shared/crud/entity-page-config.model';
import { BUILDINGS_CONFIG } from '../buildings/buildings.config';
import { COUNTERPARTIES_CONFIG } from '../counterparties/counterparties.config';

/** Header fields (plan §3.2 `unit` table), plus the two relationships this pass focuses on:
 * exactly one building per unit, and one-or-more landlords per unit (via the `unit_landlord`
 * join table -- doc §1.1 confirms a unit can have several co-owners). `building_name` /
 * `landlord_names` are backend-computed display columns, not real unit columns -- the
 * backend joins them in so the grid never has to resolve IDs to names itself.
 *
 * Both relation fields carry `relationCreateFields`, reusing Buildings'/Counterparties'
 * own field configs so a Building or Landlord can be created inline (a "+ Create new"
 * option inside the dropdown) without leaving this form -- often there isn't one yet
 * when a unit is first being entered.
 *
 * All simple scalar fields show in the grid (per request) -- only relation IDs
 * (superseded by their _name column), long free-text, and the edit-view-only panels
 * (unit spaces, related records) are hidden from it. Areas are in square metres
 * throughout (title deed / Ejari convention), not sqft. Unit spaces (layout
 * components) and related records (landlord/contract/Ejari/permits/rental
 * agreement) only render once the unit has been saved -- they need a real id. */
export const UNITS_CONFIG: EntityPageConfig = {
  title: 'Units',
  subtitle: 'One building per unit, one or more landlords per unit (doc §1.1). unit_code is auto-generated by the backend.',
  resourcePath: 'units',
  fields: [
    { key: 'unit_code', label: 'Unit code', type: 'text', showInForm: false, gridWidth: 110 },
    { key: 'unit_name', label: 'Unit name', type: 'text', required: true, gridWidth: 180 },
    {
      key: 'building_id',
      label: 'Building',
      type: 'relation-select',
      required: true,
      relationResourcePath: 'buildings',
      relationLabelKey: 'name',
      relationCreateFields: BUILDINGS_CONFIG.fields,
      showInGrid: false,
    },
    { key: 'building_name', label: 'Building', type: 'text', showInForm: false, gridWidth: 160 },
    {
      key: 'landlord_ids',
      label: 'Landlords',
      type: 'relation-multiselect',
      required: true,
      relationResourcePath: 'counterparties',
      relationLabelKey: 'name',
      relationCreateFields: COUNTERPARTIES_CONFIG.fields,
      showInGrid: false,
    },
    { key: 'landlord_names', label: 'Landlords', type: 'text', showInForm: false, gridWidth: 200, sortable: false },
    {
      key: 'type',
      label: 'Type',
      type: 'select',
      options: [
        { label: 'Studio', value: 'studio' },
        { label: '1 Bedroom', value: '1br' },
        { label: '2 Bedroom', value: '2br' },
        { label: '3 Bedroom', value: '3br' },
        { label: '4+ Bedroom', value: '4br' },
      ],
      gridWidth: 120,
    },
    {
      key: 'property_type',
      label: 'Property type',
      type: 'select',
      options: [
        { label: 'Apartment', value: 'apartment' },
        { label: 'Villa', value: 'villa' },
        { label: 'Townhouse', value: 'townhouse' },
        { label: 'Penthouse', value: 'penthouse' },
        { label: 'Other', value: 'other' },
      ],
      gridWidth: 130,
    },
    { key: 'floor_number', label: 'Floor number', type: 'text', gridWidth: 110 },
    { key: 'apartment_number', label: 'Apartment number', type: 'text', gridWidth: 140 },
    { key: 'parking_number', label: 'Parking number', type: 'text', gridWidth: 130 },
    { key: 'bathrooms', label: 'Number of bathrooms', type: 'number', gridWidth: 150 },
    { key: 'max_occupancy', label: 'Max occupancy', type: 'number', gridWidth: 130 },
    { key: 'area_sqm', label: 'Area (sqm)', type: 'number', gridWidth: 120 },
    { key: 'suite_area_sqm', label: 'Suite area (sqm)', type: 'number', gridWidth: 140 },
    { key: 'has_balcony', label: 'Balcony', type: 'boolean', gridWidth: 100 },
    { key: 'balcony_area_sqm', label: 'Balcony area (sqm)', type: 'number', gridWidth: 150 },
    {
      key: 'furnished_status',
      label: 'Condition when leased',
      type: 'select',
      options: [
        { label: 'Furnished', value: 'furnished' },
        { label: 'Unfurnished', value: 'unfurnished' },
      ],
      gridWidth: 170,
    },
    { key: 'title_deed_number', label: 'Title deed number', type: 'text', gridWidth: 150 },
    { key: 'dewa_premises_number', label: 'DEWA premises number', type: 'text', gridWidth: 170 },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Inactive', value: 'inactive' },
        { label: 'Under maintenance', value: 'under_maintenance' },
        { label: 'Exited', value: 'exited' },
      ],
      gridWidth: 150,
    },
    { key: 'handover_date', label: 'Handover date', type: 'date', gridWidth: 130 },
    { key: 'first_live_date', label: 'First-live date', type: 'date', gridWidth: 130 },

    // ---- Unit layout components (doc §1.1 `UnitSpace`) -- edit-view only ----
    { key: 'unit_spaces', label: 'Unit layout', type: 'unit-spaces', showInGrid: false },

    // ---- Related records (landlord/tenancy contract/Ejari/permits/rental agreement) -- edit-view only ----
    { key: 'related_records', label: 'Linked records', type: 'related-records', showInGrid: false },
  ],
};
