import { EntityPageConfig } from '../../shared/crud/entity-page-config.model';
import { BUILDINGS_CONFIG } from '../buildings/buildings.config';
import { COUNTERPARTIES_CONFIG } from '../counterparties/counterparties.config';

/** Header fields (plan §3.2 `unit` table), plus the two relationships this pass focuses on:
 * exactly one building per unit, and one-or-more landlords per unit (via the `unit_landlord`
 * join table -- doc §1.1 confirms a unit can have several co-owners). `building_name` /
 * `landlord_names` are backend-computed display columns, not real unit columns -- the
 * backend joins them in so the grid never has to resolve IDs to names itself.
 *
 * Both relation fields carry `relationCreateFields`, reusing Buildings'/Counterparties'
 * own field configs so a Building or Landlord can be created inline (a "+ Create new"
 * option inside the dropdown) without leaving this form -- often there isn't one yet
 * when a unit is first being entered. */
export const UNITS_CONFIG: EntityPageConfig = {
  title: 'Units',
  subtitle: 'One building per unit, one or more landlords per unit (doc §1.1). unit_code is auto-generated by the backend.',
  resourcePath: 'units',
  fields: [
    { key: 'unit_code', label: 'Unit code', type: 'text', showInForm: false, gridWidth: 110 },
    { key: 'unit_name', label: 'Unit name', type: 'text', required: true, gridWidth: 200 },
    {
      key: 'building_id',
      label: 'Building',
      type: 'relation-select',
      required: true,
      relationResourcePath: 'buildings',
      relationLabelKey: 'name',
      relationCreateFields: BUILDINGS_CONFIG.fields,
      showInGrid: false,
    },
    { key: 'building_name', label: 'Building', type: 'text', showInForm: false, gridWidth: 180 },
    {
      key: 'landlord_ids',
      label: 'Landlords',
      type: 'relation-multiselect',
      required: true,
      relationResourcePath: 'counterparties',
      relationLabelKey: 'name',
      relationCreateFields: COUNTERPARTIES_CONFIG.fields,
      showInGrid: false,
    },
    { key: 'landlord_names', label: 'Landlords', type: 'text', showInForm: false, gridWidth: 220 },
    {
      key: 'type',
      label: 'Type',
      type: 'select',
      options: [
        { label: 'Studio', value: 'studio' },
        { label: '1 Bedroom', value: '1br' },
        { label: '2 Bedroom', value: '2br' },
        { label: '3 Bedroom', value: '3br' },
        { label: '4+ Bedroom', value: '4br' },
      ],
    },
    { key: 'bathrooms', label: 'Bathrooms', type: 'number', showInGrid: false },
    { key: 'max_occupancy', label: 'Max occupancy', type: 'number', showInGrid: false },
    { key: 'area_sqft', label: 'Area (sqft)', type: 'number', showInGrid: false },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Inactive', value: 'inactive' },
        { label: 'Under maintenance', value: 'under_maintenance' },
        { label: 'Exited', value: 'exited' },
      ],
    },
    { key: 'handover_date', label: 'Handover date', type: 'date', showInGrid: false },
    { key: 'first_live_date', label: 'First-live date', type: 'date', showInGrid: false },
  ],
};
