/**
 * Phase 0 of the visual redesign (see the design-audit artifact from this conversation
 * for the full rationale). Single source of truth for the brand palette -- consumed by:
 *  - app.config.ts, to build the PrimeNG Aura preset override (definePreset)
 *  - styles.scss's `:root` block (kept in sync by hand -- ~25 values, not worth a build
 *    step at this app's scale; if these two ever drift, this file is the one that's right)
 *
 * Replaces the un-branded defaults the design audit found: PrimeNG's stock Aura preset
 * (emerald primary, slate neutrals) and hand-copied Tailwind-slate hex literals scattered
 * across ~20 components with no shared source.
 */

/** Brass -- the one accent color. Ramp generated by blending the base (#8C6B3A, sampled
 * to sit near the logo's ink) toward the surface color (light end) and ink color (dark
 * end), the same construction PrimeNG's own primitive ramps use. */
export const BRASS = {
  50: '#f8f4ef',
  100: '#efe9e0',
  200: '#dacebd',
  300: '#c3b197',
  400: '#aa916c',
  500: '#8c6b3a', // the accent itself
  600: '#765b33',
  700: '#5d492b',
  800: '#473824',
  900: '#32291e',
  950: '#25201a',
} as const;

/** Stone -- warm neutral ramp, replaces PrimeNG's default slate/zinc. Base (#6B6058) is
 * the ink-muted token; light end approaches the cream surface, dark end approaches ink. */
export const STONE = {
  50: '#f6f4f1',
  100: '#eae7e4',
  200: '#d0cbc7',
  300: '#b2aba6',
  400: '#918982',
  500: '#6b6058', // = --color-ink-muted
  600: '#5b524b',
  700: '#4a423d',
  800: '#3a3430',
  900: '#2c2724',
  950: '#221f1c',
} as const;

/** Flat semantic tokens -- the ones app code and styles.scss actually reach for day to
 * day. Colors not in BRASS/STONE (canvas, ink, line, success/warning/danger) are literals
 * because they're anchors the ramps are built from or built toward, not ramp members. */
export const DESIGN_TOKENS = {
  colorCanvas: '#F6F1EA',
  colorSurface: '#FFFDFB',
  colorSurfaceSunken: STONE[50],
  colorInk: '#1C1917',
  colorInkMuted: STONE[500],
  colorInkFaint: STONE[400],
  colorLine: '#E4DDD3',
  colorLineStrong: STONE[200],
  colorAccent: BRASS[500],
  colorAccentHover: BRASS[600],
  colorAccentTint: BRASS[100],
  colorSuccess: '#3F6B4A',
  colorSuccessTint: '#E8EFE6',
  colorWarning: '#A66A1F',
  colorWarningTint: '#F5E6CC',
  colorDanger: '#9B3A2E',
  colorDangerTint: '#F5E0DB',
  radiusSm: '6px',
  radiusMd: '10px',
  radiusLg: '14px',
  shadowElevated: '0 8px 24px rgba(28, 17, 9, 0.10)',
  fontDisplay: "'Fraunces', Georgia, serif",
  fontBody: "'Inter', -apple-system, 'Segoe UI', sans-serif",
} as const;
