"""buildings units unit spaces and tenancy contract detail fields

Revision ID: 42f5ca1696f8
Revises: 7db8dfd6dfdd
Create Date: 2026-08-11 18:37:54.343218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f5ca1696f8'
down_revision: Union[str, None] = '7db8dfd6dfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_space',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('space_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('building', sa.Column('area', sa.String(length=255), nullable=True))
    op.drop_column('building', 'minimum_stay_nights')
    op.drop_column('building', 'guest_limit')
    op.add_column('tenancy_contract', sa.Column('contract_date', sa.Date(), nullable=True))
    op.add_column('tenancy_contract', sa.Column('grace_period_start_date', sa.Date(), nullable=True))
    op.add_column('tenancy_contract', sa.Column('grace_period_end_date', sa.Date(), nullable=True))
    op.add_column('tenancy_contract', sa.Column('agency_name', sa.String(length=255), nullable=True))
    op.add_column('tenancy_contract', sa.Column('agency_renewal_charge_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True))
    op.add_column('tenancy_contract', sa.Column('landlord_maintenance_threshold', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True))
    op.add_column('tenancy_contract', sa.Column('vacating_notice_period_days', sa.Integer(), nullable=True))
    op.add_column('tenancy_contract', sa.Column('renewal_notice_period_days', sa.Integer(), nullable=True))
    op.add_column('tenancy_contract', sa.Column('early_termination_notice_days', sa.Integer(), nullable=True))
    op.add_column('tenancy_contract', sa.Column('early_termination_penalty_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True))
    op.add_column('unit', sa.Column('property_type', sa.String(length=30), nullable=True))
    op.add_column('unit', sa.Column('floor_number', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('apartment_number', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('parking_number', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('suite_area_sqm', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True))
    op.add_column('unit', sa.Column('has_balcony', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('unit', sa.Column('balcony_area_sqm', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True))
    op.add_column('unit', sa.Column('furnished_status', sa.String(length=20), nullable=True))
    op.add_column('unit', sa.Column('title_deed_number', sa.String(length=100), nullable=True))
    op.add_column('unit', sa.Column('dewa_premises_number', sa.String(length=100), nullable=True))
    # Rename rather than drop+add: the old "sqft" column already held square-metre
    # values in practice (existing data is too small to be sqft), so this was a
    # mislabel fix, not a unit conversion -- preserve the data as-is.
    op.alter_column('unit', 'area_sqft', new_column_name='area_sqm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'area_sqm', new_column_name='area_sqft')
    op.drop_column('unit', 'dewa_premises_number')
    op.drop_column('unit', 'title_deed_number')
    op.drop_column('unit', 'furnished_status')
    op.drop_column('unit', 'balcony_area_sqm')
    op.drop_column('unit', 'has_balcony')
    op.drop_column('unit', 'suite_area_sqm')
    op.drop_column('unit', 'parking_number')
    op.drop_column('unit', 'apartment_number')
    op.drop_column('unit', 'floor_number')
    op.drop_column('unit', 'property_type')
    op.drop_column('tenancy_contract', 'early_termination_penalty_amount')
    op.drop_column('tenancy_contract', 'early_termination_notice_days')
    op.drop_column('tenancy_contract', 'renewal_notice_period_days')
    op.drop_column('tenancy_contract', 'vacating_notice_period_days')
    op.drop_column('tenancy_contract', 'landlord_maintenance_threshold')
    op.drop_column('tenancy_contract', 'agency_renewal_charge_amount')
    op.drop_column('tenancy_contract', 'agency_name')
    op.drop_column('tenancy_contract', 'grace_period_end_date')
    op.drop_column('tenancy_contract', 'grace_period_start_date')
    op.drop_column('tenancy_contract', 'contract_date')
    op.add_column('building', sa.Column('guest_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('building', sa.Column('minimum_stay_nights', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('building', 'area')
    op.drop_table('unit_space')
    # ### end Alembic commands ###
