"""company profile fields and document name

Revision ID: 6e1d0857df59
Revises: fefe8b18636c
Create Date: 2026-08-11 16:28:47.047641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1d0857df59'
down_revision: Union[str, None] = 'fefe8b18636c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('document_name', sa.String(length=255), nullable=True))
    op.add_column('entity', sa.Column('brand_name', sa.String(length=255), nullable=True))
    op.add_column('entity', sa.Column('vat_number', sa.String(length=50), nullable=True))
    op.add_column('entity', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('entity', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('entity', sa.Column('manager_name', sa.String(length=255), nullable=True))
    op.add_column('entity', sa.Column('date_of_registration', sa.Date(), nullable=True))
    op.add_column('entity', sa.Column('shareholders', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'shareholders')
    op.drop_column('entity', 'date_of_registration')
    op.drop_column('entity', 'manager_name')
    op.drop_column('entity', 'phone_number')
    op.drop_column('entity', 'website')
    op.drop_column('entity', 'vat_number')
    op.drop_column('entity', 'brand_name')
    op.drop_column('attachment', 'document_name')
    # ### end Alembic commands ###
