"""building restrictions access parking move-in portal fields and building contacts amenities deposits

Revision ID: 7db8dfd6dfdd
Revises: 6e1d0857df59
Create Date: 2026-08-11 17:00:02.501521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db8dfd6dfdd'
down_revision: Union[str, None] = '6e1d0857df59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_amenity',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('access_method', sa.String(length=20), nullable=True),
    sa.Column('booking_required', sa.Boolean(), nullable=False),
    sa.Column('guest_access_permitted', sa.Boolean(), nullable=False),
    sa.Column('rules_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_contact',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('out_of_hours_contact', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_deposit',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('condition_for_release', sa.Text(), nullable=True),
    sa.Column('recovery_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('building', sa.Column('plot_number', sa.String(length=50), nullable=True))
    op.add_column('building', sa.Column('short_term_conditions', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('guest_limit', sa.Integer(), nullable=True))
    op.add_column('building', sa.Column('minimum_stay_nights', sa.Integer(), nullable=True))
    op.add_column('building', sa.Column('party_noise_rules', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('pet_rules', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('access_rules', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('building', sa.Column('move_in_permit_trigger_events', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_lead_time_days', sa.Integer(), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_cost', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_deposit_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_deposit_refundable', sa.Boolean(), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_documents_required', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_checklist', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_applied_by', sa.String(length=255), nullable=True))
    op.add_column('building', sa.Column('move_in_permit_turnaround', sa.String(length=255), nullable=True))
    op.add_column('building', sa.Column('parking_allocation_basis', sa.String(length=255), nullable=True))
    op.add_column('building', sa.Column('parking_bays_per_unit', sa.Integer(), nullable=True))
    op.add_column('building', sa.Column('parking_card_required', sa.Boolean(), nullable=True))
    op.add_column('building', sa.Column('parking_cost', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True))
    op.add_column('building', sa.Column('visitor_parking_rules', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('service_charges_note', sa.Text(), nullable=True))
    op.add_column('building', sa.Column('portal_system_name', sa.String(length=255), nullable=True))
    op.add_column('building', sa.Column('portal_username', sa.String(length=255), nullable=True))
    op.add_column('building', sa.Column('portal_reference_number', sa.String(length=100), nullable=True))
    op.add_column('building', sa.Column('portal_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'portal_notes')
    op.drop_column('building', 'portal_reference_number')
    op.drop_column('building', 'portal_username')
    op.drop_column('building', 'portal_system_name')
    op.drop_column('building', 'service_charges_note')
    op.drop_column('building', 'visitor_parking_rules')
    op.drop_column('building', 'parking_cost')
    op.drop_column('building', 'parking_card_required')
    op.drop_column('building', 'parking_bays_per_unit')
    op.drop_column('building', 'parking_allocation_basis')
    op.drop_column('building', 'move_in_permit_turnaround')
    op.drop_column('building', 'move_in_permit_applied_by')
    op.drop_column('building', 'move_in_permit_checklist')
    op.drop_column('building', 'move_in_permit_documents_required')
    op.drop_column('building', 'move_in_permit_deposit_refundable')
    op.drop_column('building', 'move_in_permit_deposit_amount')
    op.drop_column('building', 'move_in_permit_cost')
    op.drop_column('building', 'move_in_permit_lead_time_days')
    op.drop_column('building', 'move_in_permit_trigger_events')
    op.drop_column('building', 'move_in_permit_required')
    op.drop_column('building', 'access_rules')
    op.drop_column('building', 'pet_rules')
    op.drop_column('building', 'party_noise_rules')
    op.drop_column('building', 'minimum_stay_nights')
    op.drop_column('building', 'guest_limit')
    op.drop_column('building', 'short_term_conditions')
    op.drop_column('building', 'plot_number')
    op.drop_table('building_deposit')
    op.drop_table('building_contact')
    op.drop_table('building_amenity')
    # ### end Alembic commands ###
