"""tenancy contracts and ejari registration

Revision ID: a88889632bf9
Revises: 8839e68b171c
Create Date: 2026-08-11 13:28:05.238504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88889632bf9'
down_revision: Union[str, None] = '8839e68b171c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenancy_contract',
    sa.Column('contract_number', sa.String(length=30), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('renewal_of_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_annual_rent', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('instalment_count', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('security_deposit_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('agency_fee_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('agency_fee_vat_applicable', sa.Boolean(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('sublease_permitted', sa.String(length=10), nullable=False),
    sa.Column('holiday_home_permitted', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['renewal_of_id'], ['tenancy_contract.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenancy_contract_contract_number'), 'tenancy_contract', ['contract_number'], unique=True)
    op.create_table('ejari_registration',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('ejari_contract_number', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('total_fees', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grace_start_date', sa.Date(), nullable=True),
    sa.Column('grace_end_date', sa.Date(), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('annual_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('actual_contract_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('actual_annual_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('owner_number', sa.String(length=50), nullable=True),
    sa.Column('owner_nationality', sa.String(length=100), nullable=True),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('tenant_no', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('license_issuer', sa.String(length=100), nullable=True),
    sa.Column('tel_no', sa.String(length=50), nullable=True),
    sa.Column('fax_no', sa.String(length=50), nullable=True),
    sa.Column('building_name_no', sa.String(length=255), nullable=True),
    sa.Column('property_no', sa.String(length=100), nullable=True),
    sa.Column('makani_no', sa.String(length=50), nullable=True),
    sa.Column('plot_number', sa.String(length=50), nullable=True),
    sa.Column('land_dm_no', sa.String(length=50), nullable=True),
    sa.Column('land_area', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('dewa_premise_no', sa.String(length=50), nullable=True),
    sa.Column('classification_type', sa.String(length=100), nullable=True),
    sa.Column('classification_subtype', sa.String(length=100), nullable=True),
    sa.Column('usage', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['tenancy_contract.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', name='uq_ejari_registration_contract')
    )
    op.create_table('tenancy_contract_party',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['tenancy_contract.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['counterparty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'landlord_id', name='uq_tenancy_contract_party')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenancy_contract_party')
    op.drop_table('ejari_registration')
    op.drop_index(op.f('ix_tenancy_contract_contract_number'), table_name='tenancy_contract')
    op.drop_table('tenancy_contract')
    # ### end Alembic commands ###
