"""bank statement lines

Revision ID: be22ccece31e
Revises: 0e76ee18129a
Create Date: 2026-08-11 15:47:03.420826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be22ccece31e'
down_revision: Union[str, None] = '0e76ee18129a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statement_line',
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=100), nullable=True),
    sa.Column('account_iban', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('account_currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ref_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('original_ref_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_statement_line')
    # ### end Alembic commands ###
