"""counterparty groups

Revision ID: c74ed3bda788
Revises: 42f5ca1696f8
Create Date: 2026-08-12 02:00:48.808191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74ed3bda788'
down_revision: Union[str, None] = '42f5ca1696f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparty_group',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparty_group_code'), 'counterparty_group', ['code'], unique=True)
    op.add_column('counterparty', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'counterparty', 'counterparty_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'counterparty', type_='foreignkey')
    op.drop_column('counterparty', 'group_id')
    op.drop_index(op.f('ix_counterparty_group_code'), table_name='counterparty_group')
    op.drop_table('counterparty_group')
    # ### end Alembic commands ###
