"""inventory management

Revision ID: efcf515466c7
Revises: c74ed3bda788
Create Date: 2026-08-12 02:17:41.640278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcf515466c7'
down_revision: Union[str, None] = 'c74ed3bda788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('stock_tracked', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_supplier_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['counterparty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_code'), 'inventory_item', ['code'], unique=True)
    op.create_table('inventory_movement',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('location_reference', sa.String(length=255), nullable=True),
    sa.Column('to_location_type', sa.String(length=20), nullable=True),
    sa.Column('to_location_reference', sa.String(length=255), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['counterparty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_movement')
    op.drop_index(op.f('ix_inventory_item_code'), table_name='inventory_item')
    op.drop_table('inventory_item')
    # ### end Alembic commands ###
