"""Chart of Accounts seed data, transcribed from Appendix A of the source spec
(approved as drafted, doc Q257). Each tuple: (code, name, type, normal_balance,
requires_unit, is_model_b_only).

- requires_unit=True mirrors Appendix A's "[D]" flag: the doc's non-negotiable
  rule is that these accounts cannot post without a unit dimension (doc §2.0).
- is_model_b_only=True mirrors Appendix A's "[F]" flag: Model B is deferred
  entirely in v1 (plan §8), so this account exists but nothing posts to it yet.
"""

ACCOUNTS: list[tuple[str, str, str, str, bool, bool]] = [
    # ---- 1000 Assets ----
    ("1010", "Bank - current account", "asset", "debit", False, False),
    ("1020", "Cash on hand - petty cash", "asset", "debit", False, False),
    ("1030", "Cheques on hand - issued not presented", "asset", "debit", False, False),
    ("1040", "Cheques received - undeposited", "asset", "debit", False, False),
    ("1100", "Trade receivables - tenants", "asset", "debit", True, False),
    ("1110", "Trade receivables - channels", "asset", "debit", False, False),
    ("1120", "Other receivables", "asset", "debit", False, False),
    ("1130", "Utility recharges receivable - tenants", "asset", "debit", True, False),
    ("1200", "Deposits paid - landlords", "asset", "debit", True, False),
    ("1210", "Deposits paid - DEWA", "asset", "debit", True, False),
    ("1220", "Deposits paid - chiller", "asset", "debit", True, False),
    ("1230", "Deposits paid - gas", "asset", "debit", True, False),
    ("1240", "Deposits paid - building management", "asset", "debit", True, False),
    ("1300", "Prepaid rent", "asset", "debit", True, False),
    ("1310", "Prepaid agency commission", "asset", "debit", True, False),
    ("1320", "Prepaid Ejari registration fees", "asset", "debit", True, False),
    ("1330", "Prepaid DTCM permit fees", "asset", "debit", True, False),
    ("1340", "Prepaid insurance", "asset", "debit", True, False),
    ("1350", "Other prepayments and deferred setup costs", "asset", "debit", True, False),
    ("1400", "Furniture and fittings - cost", "asset", "debit", True, False),
    ("1410", "Appliances - cost", "asset", "debit", True, False),
    ("1420", "Electronics - cost", "asset", "debit", True, False),
    ("1430", "Soft furnishings and linen - cost", "asset", "debit", True, False),
    ("1440", "Fit-out and improvements - cost", "asset", "debit", True, False),
    ("1450", "IT and office equipment - cost", "asset", "debit", False, False),
    ("1480", "Accumulated depreciation - furniture and fittings", "asset", "credit", True, False),
    ("1481", "Accumulated depreciation - appliances", "asset", "credit", True, False),
    ("1482", "Accumulated depreciation - electronics", "asset", "credit", True, False),
    ("1483", "Accumulated depreciation - soft furnishings and linen", "asset", "credit", True, False),
    ("1484", "Accumulated depreciation - fit-out", "asset", "credit", True, False),
    ("1485", "Accumulated depreciation - IT and office equipment", "asset", "credit", False, False),
    ("1500", "Inventory - consumables and amenities", "asset", "debit", False, False),
    ("1600", "Input VAT - recoverable", "asset", "debit", False, False),
    ("1610", "Input VAT - residual, pending apportionment", "asset", "debit", False, False),
    ("1620", "Input VAT - reverse charge (self-accounted)", "asset", "debit", False, False),
    # ---- 2000 Liabilities ----
    ("2010", "Trade payables - suppliers", "liability", "credit", False, False),
    ("2020", "Payables - landlords (rent due)", "liability", "credit", True, False),
    ("2030", "Accrued expenses", "liability", "credit", True, False),
    ("2040", "Accrued utilities - unbilled", "liability", "credit", True, False),
    ("2100", "Deferred revenue - guest stays", "liability", "credit", True, False),
    ("2110", "Deferred revenue - long-term rent received in advance", "liability", "credit", True, False),
    ("2200", "Security deposits held - tenants", "liability", "credit", True, False),
    ("2210", "Guest deposits and pre-authorisations held", "liability", "credit", True, False),
    ("2300", "Tourism Dirham payable", "liability", "credit", True, False),
    ("2400", "Output VAT - payable", "liability", "credit", False, False),
    ("2410", "Output VAT - reverse charge (self-accounted)", "liability", "credit", False, False),
    ("2500", "Corporate tax payable", "liability", "credit", False, False),
    ("2600", "Payroll liabilities", "liability", "credit", False, False),
    ("2700", "Loans and financing", "liability", "credit", False, False),
    # ---- 3000 Equity ----
    ("3010", "Share capital", "equity", "credit", False, False),
    ("3020", "Shareholder current account", "equity", "credit", False, False),
    ("3030", "Retained earnings", "equity", "credit", False, False),
    ("3040", "Current year result", "equity", "credit", False, False),
    # ---- 4000 Revenue ----
    ("4010", "Accommodation revenue - short-term", "revenue", "credit", True, False),
    ("4020", "Cleaning fee revenue - guests", "revenue", "credit", True, False),
    ("4030", "Service fee revenue", "revenue", "credit", True, False),
    ("4040", "Other guest fees", "revenue", "credit", True, False),
    ("4050", "Cancellation and no-show income", "revenue", "credit", True, False),
    ("4060", "Damage recovery income", "revenue", "credit", True, False),
    ("4100", "Rental income - long-term", "revenue", "credit", True, False),
    ("4110", "Utility recharge income - tenants", "revenue", "credit", True, False),
    ("4120", "Late payment penalty income", "revenue", "credit", True, False),
    ("4200", "Management commission income", "revenue", "credit", True, True),
    # ---- 5000 Direct costs (all unit-dimensioned) ----
    ("5010", "Rent - landlords", "cost", "debit", True, False),
    ("5020", "OTA commission - room revenue", "cost", "debit", True, False),
    ("5030", "OTA commission - cleaning fee", "cost", "debit", True, False),
    ("5040", "OTA commission - other", "cost", "debit", True, False),
    ("5050", "OTA payment / processing charges", "cost", "debit", True, False),
    ("5100", "Checkout cleaning", "cost", "debit", True, False),
    ("5110", "Cleaning service - other", "cost", "debit", True, False),
    ("5120", "Laundry and linen", "cost", "debit", True, False),
    ("5130", "Consumables and guest amenities", "cost", "debit", True, False),
    ("5200", "Maintenance and repairs", "cost", "debit", True, False),
    ("5210", "Check-in assistance", "cost", "debit", True, False),
    ("5300", "Tourism Dirham - absorbed", "cost", "debit", True, False),
    ("5400", "DEWA - housing fee", "cost", "debit", True, False),
    ("5410", "DEWA - water", "cost", "debit", True, False),
    ("5420", "DEWA - electricity", "cost", "debit", True, False),
    ("5430", "DEWA - sewerage", "cost", "debit", True, False),
    ("5440", "Gas", "cost", "debit", True, False),
    ("5450", "Chiller", "cost", "debit", True, False),
    ("5460", "Internet", "cost", "debit", True, False),
    ("5500", "Insurance - unit", "cost", "debit", True, False),
    ("5600", "Amortisation - agency commission", "cost", "debit", True, False),
    ("5610", "Amortisation - Ejari fees", "cost", "debit", True, False),
    ("5620", "Amortisation - DTCM permit fees", "cost", "debit", True, False),
    ("5630", "Amortisation - other setup costs", "cost", "debit", True, False),
    ("5700", "Depreciation - unit assets", "cost", "debit", True, False),
    ("5800", "Access card and replacement fees", "cost", "debit", True, False),
    ("5850", "Refunds to guests", "cost", "debit", True, False),
    ("5900", "Other direct costs", "cost", "debit", True, False),
    # ---- 6000 Overheads (allocated to units in the reporting layer only, doc §7.3) ----
    ("6010", "Salaries and wages", "cost", "debit", False, False),
    ("6020", "Staff benefits and visas", "cost", "debit", False, False),
    ("6100", "Office rent and utilities", "cost", "debit", False, False),
    ("6200", "Software and subscriptions", "cost", "debit", False, False),
    ("6300", "Marketing and photography", "cost", "debit", False, False),
    ("6400", "Professional fees - legal, audit, tax", "cost", "debit", False, False),
    ("6500", "Bank charges", "cost", "debit", False, False),
    ("6600", "Licences and government fees - company level", "cost", "debit", False, False),
    ("6700", "Telephone and communications", "cost", "debit", False, False),
    ("6800", "Travel and transport", "cost", "debit", False, False),
    ("6900", "Other administrative expenses", "cost", "debit", False, False),
    # ---- 7000 / 8000 Other and tax ----
    ("7010", "Interest income", "other", "credit", False, False),
    ("7020", "Interest expense", "other", "debit", False, False),
    ("7030", "Gain / loss on disposal of assets", "other", "debit", False, False),
    ("7040", "Write-off - unrecovered deposits", "other", "debit", False, False),
    ("7050", "Bad debt expense", "other", "debit", False, False),
    ("8010", "Corporate tax expense", "other", "debit", False, False),
]

CONTROL_ACCOUNT_CODES = {"1030", "1040", "1100", "2010"}
